#!/bin/bash

source "../../set_tools.sh"

cp ../../namelist/*.nml ./

#--------------------------------
# MOMturb.nml
#--------------------------------
# airsea.nml
nml="airsea.nml"
${cmd_nmlchange} -f ${nml} -e heat_method -v 2
${cmd_nmlchange} -f ${nml} -e heatflux_file -v 'heatflux_file.dat'
${cmd_nmlchange} -f ${nml} -e swr_method -v 2
${cmd_nmlchange} -f ${nml} -e albedo_method -v 0
${cmd_nmlchange} -f ${nml} -e swr_file -v 'swr_file.dat'
${cmd_nmlchange} -f ${nml} -e momentum_method -v 2
${cmd_nmlchange} -f ${nml} -e const_tx -v 0.1027
${cmd_nmlchange} -f ${nml} -e momentumflux_file -v 'tau_file.dat'
${cmd_nmlchange} -f ${nml} -e precip_method -v 2
${cmd_nmlchange} -f ${nml} -e precip_file -v 'precip_file.dat'
${cmd_nmlchange} -f ${nml} -e precip_factor -v 2.77778e-7
${cmd_nmlchange} -f ${nml} -e sst_method -v 0
${cmd_nmlchange} -f ${nml} -e sst_file -v ''
${cmd_nmlchange} -f ${nml} -e sss_method -v 0
${cmd_nmlchange} -f ${nml} -e sss_file -v ''
${cmd_nmlchange} -f ${nml} -e u10_method -v 0
${cmd_nmlchange} -f ${nml} -e const_u10 -v 10
${cmd_nmlchange} -f ${nml} -e u10_file -v ''
#--------------------------------
# epbl.nml
#--------------------------------
# gotmmean.nml
#--------------------------------
# gotmrun.nml
nml="gotmrun.nml"
${cmd_nmlchange} -f ${nml} -e title -v 'BOB'
${cmd_nmlchange} -f ${nml} -e nlev -v 128
${cmd_nmlchange} -f ${nml} -e dt -v 1800
${cmd_nmlchange} -f ${nml} -e name -v 'BOB'
${cmd_nmlchange} -f ${nml} -e latitude -v 13.5
${cmd_nmlchange} -f ${nml} -e longitude -v 81
${cmd_nmlchange} -f ${nml} -e depth -v 300.0
${cmd_nmlchange} -f ${nml} -e start -v '2016-05-01 06:30:00'
${cmd_nmlchange} -f ${nml} -e stop -v '2016-05-30 17:30:00'
${cmd_nmlchange} -f ${nml} -e nsave -v 6
${cmd_nmlchange} -f ${nml} -e sync_out -v 0
${cmd_nmlchange} -f ${nml} -e eq_state_method -v 4
#--------------------------------
# gotmturb.nml
#--------------------------------
# jhl.nml
#--------------------------------
# kpp.nml
#--------------------------------
# langmuir.nml
nml="langmuir.nml"
${cmd_nmlchange} -f ${nml} -e langmuir_number_method -v 3
#--------------------------------
# obs.nml
nml="obs.nml"
${cmd_nmlchange} -f ${nml} -e s_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e s_prof_file -v 'sprof_file.dat'
${cmd_nmlchange} -f ${nml} -e t_prof_method -v 2
${cmd_nmlchange} -f ${nml} -e t_prof_file -v 'tprof_file.dat'
${cmd_nmlchange} -f ${nml} -e ustokes_method -v 0
${cmd_nmlchange} -f ${nml} -e spec_file -v ''
#--------------------------------
# osm.nml
nml="osm.nml"
${cmd_nmlchange} -f ${nml} -e h_i -v 20.0
#--------------------------------
# seagrass.nml
#--------------------------------
