#!/bin/bash
# Run GOTM using preprocessed data for a ocean site in Bay of Bengal (13.5N 81E)
# Require a base case which contains the preprocessed input data and namelists
# Zhihua Zheng, Nov. 7 2018

#######################################################################
#                              Set paths                              #
#######################################################################

# setup paths and tools
source "../../set_tools.sh"

# directory of base case
basecase="${GOTMWORK_ROOT}/data/BOB" # BOB forcing

# activate conda environment
source activate gotmwork-pyenv

#######################################################################
#                           Set parameters                            #
#######################################################################

# name of the dataset
title="BOB"

# set levels, grid zooming at surface
nlev=128
ddu=2
ddl=0

# run parameters
#dt=900
dt=1800
nsave=6

# starting and ending date - in the format of YYYYMMDD
datestart="20160510"
dateend="20160527"

# name of the turbulence model
# turbmethod="KPP-GOTM"
# turbmethod="KPP-ROMS"
# turbmethod="KPP-CVMix"
# turbmethod="KPPLT-EFACTOR"
# turbmethod="KPPLT-ENTR"
# turbmethod="KPPLT-RWHGK"
# turbmethod="OSMOSIS"
# turbmethod="JHL"
# turbmethod="EPBL"
# turbmethod="EPBL-LT"
 turbmethod="SMC"
# turbmethod="SMCLT"
# turbmethod="K-EPSILON-SG"

# output file name
outname="gotm_out"

# case name
casename="${title}_${turbmethod}_${datestart}-${dateend}"

#######################################################################
#                        Preprocess input data                        #
#######################################################################

# create run directory
rundir="${GOTMRUN_ROOT}/${casename}"
mkdir -p ${rundir}
cd ${rundir}

# copy base case
cp ${basecase}/* ./

# decompress input data
for f in *.gz; do
    gunzip -f ${f}
done

# set run parameters
start_time="${datestart:0:4}-${datestart:4:2}-${datestart:6:2} 21:30:00"
stop_time="${dateend:0:4}-${dateend:4:2}-${dateend:6:2} 11:30:00"
${cmd_nmlchange} -f gotmrun.nml -e start -v "${start_time}"
${cmd_nmlchange} -f gotmrun.nml -e stop -v "${stop_time}"
${cmd_nmlchange} -f gotmrun.nml -e title -v ${title}
${cmd_nmlchange} -f gotmrun.nml -e out_fn -v ${outname}
${cmd_nmlchange} -f gotmrun.nml -e dt -v ${dt}
${cmd_nmlchange} -f gotmrun.nml -e nsave -v ${nsave}
${cmd_nmlchange} -f gotmrun.nml -e nlev -v ${nlev}
${cmd_nmlchange} -f gotmmean.nml -e ddu -v ${ddu}
${cmd_nmlchange} -f gotmmean.nml -e ddl -v ${ddl}

# set turbulence method
source ${scpt_case_turbmethod}

#######################################################################
#                              Run GOTM                               #
#######################################################################
${cmd_gotm} 2> log.${outname}

#######################################################################
#                           Postprocessing                            #
#######################################################################

# plot surface forcing and profiles
source ${scpt_case_postproc}

# deactivate conda environment
source deactivate gotmwork-pyenv
